export const propostaDados = [
  {
    "ID da Proposta": "1",
    "Nome/Razão Social do Cliente": "Empresa ABC LTDA",
    "CPF/CNPJ do Cliente": "123.456.789-00",
    "Produto": "Empréstimo Empresarial",
    "Valor da Proposta": "R$ 100.000,00",
    "Status da Proposta": "Em análise",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando documentação",
    "SLA": "48 horas",
    "Analista Responsável": "João Silva",
    "Data Criação": "2024-07-15",
    "Criada Por (responsável)": "Maria Souza"
  },
  {
    "ID da Proposta": "2",
    "Nome/Razão Social do Cliente": "Comércio XYZ ME",
    "CPF/CNPJ do Cliente": "987.654.321-00",
    "Produto": "Financiamento de Veículos",
    "Valor da Proposta": "R$ 50.000,00",
    "Status da Proposta": "Aprovada",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando assinatura",
    "SLA": "24 horas",
    "Analista Responsável": "Ana Costa",
    "Data Criação": "2024-07-14",
    "Criada Por (responsável)": "Carlos Lima"
  },
  {
    "ID da Proposta": "3",
    "Nome/Razão Social do Cliente": "Indústria Delta SA",
    "CPF/CNPJ do Cliente": "111.222.333-44",
    "Produto": "Crédito Imobiliário",
    "Valor da Proposta": "R$ 200.000,00",
    "Status da Proposta": "Em análise",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando aprovação",
    "SLA": "72 horas",
    "Analista Responsável": "Roberto Dias",
    "Data Criação": "2024-07-13",
    "Criada Por (responsável)": "Fernanda Santos"
  },
  {
    "ID da Proposta": "4",
    "Nome/Razão Social do Cliente": "Construtora Beta LTDA",
    "CPF/CNPJ do Cliente": "555.666.777-88",
    "Produto": "Capital de Giro",
    "Valor da Proposta": "R$ 150.000,00",
    "Status da Proposta": "Reprovada",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando reenvio",
    "SLA": "36 horas",
    "Analista Responsável": "Mariana Oliveira",
    "Data Criação": "2024-07-12",
    "Criada Por (responsável)": "Lucas Pereira"
  },
  {
    "ID da Proposta": "5",
    "Nome/Razão Social do Cliente": "Serviços Gamma EIRELI",
    "CPF/CNPJ do Cliente": "222.333.444-55",
    "Produto": "Cheque Especial",
    "Valor da Proposta": "R$ 10.000,00",
    "Status da Proposta": "Aprovada",
    "Sub-Status da Proposta (funil da mesa)": "Documentação completa",
    "SLA": "12 horas",
    "Analista Responsável": "Paula Almeida",
    "Data Criação": "2024-07-11",
    "Criada Por (responsável)": "Felipe Fernandes"
  },
  {
    "ID da Proposta": "6",
    "Nome/Razão Social do Cliente": "Transportes Epsilon Ltda",
    "CPF/CNPJ do Cliente": "444.555.666-77",
    "Produto": "Crédito Rural",
    "Valor da Proposta": "R$ 80.000,00",
    "Status da Proposta": "Em análise",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando validação",
    "SLA": "24 horas",
    "Analista Responsável": "Ricardo Lopes",
    "Data Criação": "2024-07-10",
    "Criada Por (responsável)": "Gabriela Mendes"
  },
  {
    "ID da Proposta": "7",
    "Nome/Razão Social do Cliente": "Tecnologia Zeta ME",
    "CPF/CNPJ do Cliente": "888.999.000-11",
    "Produto": "Crédito Consignado",
    "Valor da Proposta": "R$ 60.000,00",
    "Status da Proposta": "Reprovada",
    "Sub-Status da Proposta (funil da mesa)": "Documentação pendente",
    "SLA": "48 horas",
    "Analista Responsável": "Aline Souza",
    "Data Criação": "2024-07-09",
    "Criada Por (responsável)": "Bruno Costa"
  },
  {
    "ID da Proposta": "8",
    "Nome/Razão Social do Cliente": "Educação Eta LTDA",
    "CPF/CNPJ do Cliente": "111.333.555-77",
    "Produto": "Leasing",
    "Valor da Proposta": "R$ 90.000,00",
    "Status da Proposta": "Em análise",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando avaliação",
    "SLA": "72 horas",
    "Analista Responsável": "Claudia Martins",
    "Data Criação": "2024-07-08",
    "Criada Por (responsável)": "Renato Silva"
  },
  {
    "ID da Proposta": "9",
    "Nome/Razão Social do Cliente": "Consultoria Theta ME",
    "CPF/CNPJ do Cliente": "222.444.666-88",
    "Produto": "Fomento Mercantil",
    "Valor da Proposta": "R$ 120.000,00",
    "Status da Proposta": "Aprovada",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando liberação",
    "SLA": "36 horas",
    "Analista Responsável": "Daniela Rocha",
    "Data Criação": "2024-07-07",
    "Criada Por (responsável)": "Vitor Nascimento"
  },
  {
    "ID da Proposta": "10",
    "Nome/Razão Social do Cliente": "Saúde Iota SA",
    "CPF/CNPJ do Cliente": "555.777.999-00",
    "Produto": "Microcrédito",
    "Valor da Proposta": "R$ 30.000,00",
    "Status da Proposta": "Em análise",
    "Sub-Status da Proposta (funil da mesa)": "Aguardando parecer",
    "SLA": "24 horas",
    "Analista Responsável": "Vanessa Correia",
    "Data Criação": "2024-07-06",
    "Criada Por (responsável)": "Marcelo Braga"
  }
];
